"""empty message

Revision ID: 3b6ad66f7dac
Revises: 4b01613bfbed
Create Date: 2014-02-11 00:17:41.015532

"""

# revision identifiers, used by Alembic.
revision = '3b6ad66f7dac'
down_revision = '4b01613bfbed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scope',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scope')
    ### end Alembic commands ###
