"""empty message

Revision ID: 50f9e07d186e
Revises: 3b6ad66f7dac
Create Date: 2014-03-03 02:29:01.773326

"""

# revision identifiers, used by Alembic.
revision = '50f9e07d186e'
down_revision = '3b6ad66f7dac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('admin_access', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'admin_access')
    ### end Alembic commands ###
